export const LOGIN = 'LOGIN';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const LOGOUT = 'LOGOUT';
export const SIGN_UP = 'SIGN_UP';
export const RENEW_TOKEN = 'RENEW_TOKEN';

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_PREFER = 'CHANGE_PREFER';

export const HIDE_POST = 'HIDE_POST';
export const UNHIDE_POST = 'UNHIDE_POST';

export const REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const OPEN_ADMIN_MODAL = 'OPEN_ADMIN_MODAL';
export const CLOSE_ADMIN_MODAL = 'CLOSE_ADMIN_MODAL';

export const OPEN_ACCOUNT_MODAL = 'OPEN_ACCOUNT_MODAL';
export const CLOSE_ACCOUNT_MODAL = 'CLOSE_ACCOUNT_MODAL';

export const TO_PAGE_404 = 'TO_PAGE_404';
export const PAGE_404 = 'PAGE_404';

export const REQUEST_GET_POST = 'REQUEST_GET_POST';
export const REQUEST_GET_POSTS = 'REQUEST_GET_POSTS';
export const REQUEST_GET_REACTIONS = 'REQUEST_GET_REACTIONS';
export const REQUEST_GET_COMMENTS = 'REQUEST_GET_COMMENTS';
export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const REQUEST_SUBSCRIBE = 'REQUEST_SUBSCRIBE';
export const REQUEST_CHECK_IS_POST_SUBSCRIBED = 'REQUEST_CHECK_IS_POST_SUBSCRIBED';
export const REQUEST_GET_SUBSCRIPTION = 'REQUEST_GET_SUBSCRIPTION';
export const REQUEST_DELETE_ACCOUNT = 'REQUEST_DELETE_ACCOUNT';

export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_USER = 'GET_USER';
export const GET_REACTIONS = 'GET_REACTIONS';
export const GET_COMMENTS = 'GET_COMMENTS';
export const SUBSCRIBED_POST = 'SUBSCRIBED_POST';
export const GET_POST_SUBSCRIPTION = 'GET_POST_SUBSCRIPTION';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const COMMENT_SUBMITTED = 'COMMENT_SUBMITTED';

export const SUBMIT_POST = 'SUBMIT_POST';
export const POST_CREATED = 'POST_CREATED';

export const SUBMIT_REACTION = 'SUBMIT_REACTION';
export const REACTION_REACTED = 'REACTION_REACTED';

export const SUB_EXIST = 'SUB_EXIST';

export const REPLY_TO = 'REPLY_TO';

export const REQUEST_LOCK_POST = 'REQUEST_LOCK_POST';
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const REQUEST_MOVE_POST = 'REQUEST_MOVE_POST';
export const REQUEST_CHANGE_POST_LANGUAGE = 'REQUEST_CHANGE_POST_LANGUAGE';

export const LOCK_POST = 'LOCK_POST';
export const DELETE_POST = 'DELETE_POST';
export const MOVE_POST = 'MOVE_POST';
export const CHANGE_POST_LANGUAGE = 'CHANGE_POST_LANGUAGE';

export const REQUEST_CHANGE_AVATAR = 'REQUEST_CHANGE_AVATAR';
export const AVATAR_CHANGED = 'AVATAR_CHANGED';

export const CORRECT_REDUCERS_VERSION = 'CORRECT_REDUCERS_VERSION';
