export const LOGIN = 'LOGIN';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';
export const CHANG_LANGUAGE = 'CHANG_LANGUAGE';

export const TO_PAGE_404 = 'TO_PAGE_404';
export const PAGE_404 = 'PAGE_404';

export const REQUEST_GET_POST = 'REQUEST_GET_POST';
export const REQUEST_GET_POSTS = 'REQUEST_GET_POSTS';
export const REQUEST_REACTIONS = 'REQUEST_REACTIONS';
export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_REACTIONS = 'GET_REACTIONS';

export const REQUEST_GET_COMMENTS = 'REQUEST_GET_COMMENTS';
export const GET_COMMENTS = 'GET_COMMENTS';

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const COMMENT_SUBMITTED = 'COMMENT_SUBMITTED';

export const SUBMIT_POST = 'SUBMIT_POST';
export const POST_CREATED = 'POST_CREATED';

export const SUBMIT_REACTION = 'SUBMIT_REACTION';
export const REACTION_REACTED = 'REACTION_REACTED';

export const SUB_EXIST = 'SUB_EXIST';

export const REPLY_TO = 'REPLY_TO';