export const LOGIN = 'LOGIN';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const LOGOUT = 'LOGOUT';
export const SIGN_UP = 'SIGN_UP';
export const RENEW_TOKEN = 'RENEW_TOKEN';

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const OPEN_ADMIN_MODAL = 'OPEN_ADMIN_MODAL';
export const CLOSE_ADMIN_MODAL = 'CLOSE_ADMIN_MODAL';

export const TO_PAGE_404 = 'TO_PAGE_404';
export const PAGE_404 = 'PAGE_404';

export const REQUEST_GET_POST = 'REQUEST_GET_POST';
export const REQUEST_GET_POSTS = 'REQUEST_GET_POSTS';
export const REQUEST_GET_REACTIONS = 'REQUEST_GET_REACTIONS';
export const REQUEST_GET_COMMENTS = 'REQUEST_GET_COMMENTS';
export const REQUEST_GET_USER = 'REQUEST_GET_USER';

export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_USER = 'GET_USER';
export const GET_REACTIONS = 'GET_REACTIONS';
export const GET_COMMENTS = 'GET_COMMENTS';

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const COMMENT_SUBMITTED = 'COMMENT_SUBMITTED';

export const SUBMIT_POST = 'SUBMIT_POST';
export const POST_CREATED = 'POST_CREATED';

export const SUBMIT_REACTION = 'SUBMIT_REACTION';
export const REACTION_REACTED = 'REACTION_REACTED';

export const SUB_EXIST = 'SUB_EXIST';

export const REPLY_TO = 'REPLY_TO';

export const REQUEST_LOCK_POST = 'REQUEST_LOCK_POST';
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const REQUEST_MOVE_POST = 'REQUEST_MOVE_POST';

export const LOCK_POST = 'LOCK_POST';
